server:
  port: 8821

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: ludd-oj-user-service
          uri: lb://ludd-oj-user-service
          predicates:
            - Path=/api/user/**

        - id: ludd-oj-question-service
          uri: lb://ludd-oj-question-service
          predicates:
            - Path=/api/question/**

        - id: ludd-oj-submit-service
          uri: lb://ludd-oj-submit-service
          predicates:
            - Path=/api/submit/**