server:
  port: 8321

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: root
    password: root
    listener:
      simple:
        prefetch: 1
      direct:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 6000
          max-interval: 6000
  application:
    name: judge-service


judge:
  judge-machine-url: http://localhost:8221


