server:
  port: 8621

user:
  root:
    password: ${ROOT_PASSWORD:luddoj}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/oj-ludd
  jpa:
#    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true

  application:
    name: ludd-oj-user-service


